version: '3.9'

services: 
  salt-master:
    hostname: salt-master
    build:
      context: .
      dockerfile: Dockerfile.master
    networks:
      - salt-network
    volumes:
      - ./files/etc/salt:/srv/salt:rw
    restart: always
  salt-minion-1:
    hostname: salt-minion-1
    build:
      context: .
      dockerfile: Dockerfile.minion
    networks:
      - salt-network
    depends_on:
      - salt-master
    restart: always
  salt-minion-2:
    hostname: salt-minion-2
    build:
      context: .
      dockerfile: Dockerfile.minion
    networks:
      - salt-network
    depends_on:
      - salt-master
    restart: always
networks:
  salt-network: {}