version: '3.7'

services: 
  salt-master:
    build:
      context: .
      dockerfile: Dockerfile.master
    networks:
      - salt-network
  salt-minion:
    build:
      context: .
      dockerfile: Dockerfile.minion
    networks:
      - salt-network
    depends_on:
      - salt-master
networks:
  salt-network: {}